spring.application.name=MedicalPlatform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medical_platform}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:ThisIsASecretKeyForMedicalPlatformJwtThisIsASecretKeyForMedicalPlatformJwt}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}